# Generated by Django 5.1.4 on 2024-12-28 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Введите, куда вы хотите записаться', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Запись вашего питомца на прием'),
        ),
    ]
